aws-for-fluent-bit:
  serviceAccount:
    create: false

  cloudWatch:

  firehose:

  kinesis:

  elasticsearch:
  
  filter:
    extraFilters: |
    Use_Kubelet = true
    Kubelet_Port = 10250
    
  hostNetwork: true
